# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "ahci" "xhci_pci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-b8550cf0-66a5-444e-b01c-e9bb4784acbf";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-b8550cf0-66a5-444e-b01c-e9bb4784acbf".device = "/dev/disk/by-uuid/b8550cf0-66a5-444e-b01c-e9bb4784acbf";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/45D5-F0CF";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-9106207c-8d6a-493c-8a5a-84ab8d233b19"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
